name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Debug - List directory structure after build
        run: |
          echo "Listing the entire workspace after building:"
          ls -R
          echo "Listing frontend directory specifically:"
          ls -R frontend
          echo "Listing frontend/build directory specifically:"
          ls -R frontend/build || echo "Build directory does not exist"

  deploy:
    name: Deploy to Dev Environment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug - List structure before deploying
        run: ls -R

      - name: Deploy Frontend to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: 'us-west-2'
        run: |
          aws s3 sync frontend/build s3://dev-frontend-bucket-oluwa --acl public-read
